### ISSUE TITLE
Can show me a example about the metric setting?

### ISSUE THREAD

**Issue by b1gcat** [gretamosa/gretamosa-topology-panel#1]

**Comment by gretamosa** [comment]
I'm migrating the plugin to new Grafana 6.x versions. Once finished, I will update README with some examples.

**Comment by b1gcat** [comment]
@gretamosa good news!

if it support 5.4.3 +, it will be a great news! :)

**Comment by gretamosa** [comment]
I've committed some fixes and update screenshots in README.md. Re-open issue if needed. https://github.com/gretamosa/gretamosa-topology-panel/commit/4c03c22a0092e72fdea0fc9c0eab157a2d4e41eb
