### ISSUE TITLE
I don't plan to upgrade to 6. Can you show me the metric configuration of the current version?

### ISSUE THREAD

**Issue by webliuxiang** [gretamosa/gretamosa-topology-panel#2]

**Comment by webliuxiang** [comment]
Or show the data format. Thank you

**Comment by gretamosa** [comment]
I've committed some fixes and update screenshots in README.md. The easiest way to use this plugin is with Raw Document in Elasticsearch with your filters and select your source and destination fields (i.e. source host and destination host) and edge metric field (i.e. bytes). 

If you want to filter in topology, you will need an adhoc filter in Grafana.

Re-open the issue if needed.
