### ISSUE TITLE
Panel plugin with id gretamosa-topology-panel could not be found

### ISSUE THREAD

**Issue by jmgonzalezp** [gretamosa/gretamosa-topology-panel#3]
Hello! I think I have followed instructions to install the plugin, but when i try to use the panel, grafana shows this error "Panel plugin with id gretamosa-topology-panel could not be found". 

How can I troubleshoot this problem?

Thanks.

**Comment by gretamosa** [comment]
It's related with #1 . With v6 upgrade, some plugins needs to be migrated to the new model of plugins in Grafana. I'm working on it and I hope to release a new version soon.

**Comment by gretamosa** [comment]
I've committed somes fixes and update README.md. They must close your issue. Re-open if needed.
