### ISSUE TITLE
Panel plugin with id gretamosa-topology-panel could not be found

### ISSUE THREAD

**Issue by ITNinjaGirl** [gretamosa/gretamosa-topology-panel#5]
I installed from the CLI and got the above error.  I then removed the plugin and built from Git repo, but after running npm run build - I do not see the plugin in the folder.   I do not get any errors during the build process.

**Comment by gretamosa** [comment]
Follow the instructions in the REAME.md to complete the installation, it is the best way.

1. git clone ...
2. npm i 
3. npm run build (you will need install grunt)
4. restart grafana

**Comment by ITNinjaGirl** [comment]
okay, I realized what happened.  All good.  It looks like the build process did not copy the compiled plugin.  Once I copied it over and restarted Grafana - it works.
